layoutapp/config/routes.rb
Rails.application.routes.draw do
  get 'about', controller: :static, action: :about, alias: 'about'
  get 'services', controller: :static, action: :services, alias: 'services'
  root 'home#index'

end

layoutapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

layoutapp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home-layout'
  def index
  end
end

layoutapp/app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
  end

  def services
  end
end

layoutapp/app/helpers/application_helper.rb
module ApplicationHelper
end

layoutapp/app/helpers/home_helper.rb
module HomeHelper
end

layoutapp/app/helpers/static_helper.rb
module StaticHelper
end

layoutapp/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

layoutapp/app/views/layouts/_menu.html.erb
<ul>
  <li style="display: inline"><%= link_to 'Home', root_path %></li>
  <li style="display: inline"><%= link_to 'About', about_path %></li>
  <li style="display: inline"><%= link_to 'Services', services_path %></li>
</ul>

layoutapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Layoutapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

layoutapp/app/views/layouts/home-layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Layoutapp home-layout</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/menu' %>
<%= yield %>

</body>
</html>