restapp-sprint1/config/routes.rb
Rails.application.routes.draw do
  resources :profiles, only: [:edit, :update]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'pages/index'

  get 'pages/about_us'

  get 'pages/faq'

  get 'pages/tos'

  get 'pages/contact_us'
  
  root 'pages#index'
  

end

restapp-sprint1/app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :integer          not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  born_at    :datetime
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Profile < ActiveRecord::Base
  belongs_to :user
  def full_name
    #self.first_name + " " + self.last_name
    return "#{self.first_name} #{self.last_name}"
  end
end

restapp-sprint1/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
  enum role: [:user, :operator, :chef, :admin]
  after_initialize :set_default_role

  def set_default_role
    self.role ||= :user
  end
  def default_profile
    if self.profile.nil?
      profile = Profile.new
      profile.user = self
      profile.save
      self.save      
    end
    self.profile
  end
  def friendly_name
    if self.default_profile.first_name.nil?
      self.email
    else
      self.profile.full_name
    end
  end  
end

restapp-sprint1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

restapp-sprint1/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'internal', :except => [:index]
  def index
  end

  def about_us
  end

  def faq
  end

  def tos
  end

  def contact_us
  end
end

restapp-sprint1/app/controllers/profiles_controller.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :integer          not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  born_at    :datetime
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        #format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.html { redirect_to root_url, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :born_at, :user_id)
    end
end

restapp-sprint1/app/helpers/application_helper.rb
module ApplicationHelper
end

restapp-sprint1/app/helpers/pages_helper.rb
module PagesHelper
end

restapp-sprint1/app/helpers/profiles_helper.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :integer          not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  born_at    :datetime
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module ProfilesHelper
end

restapp-sprint1/app/views/layouts/_authentication.html.erb
<p class="navbar-text navbar-right">
  <% if current_user %>
      Signed in as <%= link_to current_user.friendly_name, edit_profile_path(current_user.default_profile), class: "navbar-link" %>
      <%= " | " %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "navbar-link" %>
  <% else %>
      <%= link_to "Sign in", new_user_session_path, class: "navbar-link" %>
  <% end %>
</p>

restapp-sprint1/app/views/layouts/_menu.html.erb
<li><%= link_to "About us", pages_about_us_path  %></li>
<li><%= link_to "FAQ", pages_faq_path  %></li>
<li><%= link_to "Terms of Service", pages_tos_path  %></li>
<li><%= link_to "Contact us", pages_contact_us_path  %></li>

restapp-sprint1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RestappSprint1" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index">RestappSprint1</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%= render 'layouts/menu' %>
          </ul>
          <%= render 'layouts/authentication' %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
<!--       <p class="notice"><%= notice %></p>
          #<p class="alert"><%= alert %></p> -->
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <%= render 'layouts/menu' %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

restapp-sprint1/app/views/layouts/internal.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RestappSprint1" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index">RestappSprint1</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%= render 'layouts/menu' %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
<!--          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p> -->
          <div class="page-header">
            <h1><%= yield :header_title %> <small><%= yield :header_sub_title %></small></h1>
          </div>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <%= render 'layouts/menu' %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

restapp-sprint1/app/views/pages/about_us.html.erb
<%= content_for :header_title do %>
  About Us
<% end %>
<%= content_for :header_sub_title do %>
  About sub title
<% end %>
<h2>Our history</h2>

<p>Opened in 1999, Restaurant Wok & Wine is a casual fine dining restaurant, offering eclectic American cuisine and warm hospitality in a rustic historically preserved building. A high, open beam ceiling, exposed brick and concrete floors display the original space, while an open kitchen, banquette seating and gentle lighting contribute to an intimate and contemporary feel.</p>

<p>We specialize in three course tasting menus, allowing the customer to select any three dishes from the menu for $55 per person. A la Carte dining is also available.</p>

<p>Our food is sourced from top quality seasonal ingredients, featuring a high percentage of local and organic products. Our menu changes every six to eight weeks, offering a mix of new and signature dishes. We consider Wok & Wine to be a truly “American” restaurant honoring many different cooking traditions and interpreting them with our unique creative vision.</p>

<p>Inspired by great artisanal foods of the world. We craft all of our stocks, sauces, breads, pastries and ice creams from scratch on a daily basis. We also strive to support other artisanal producers when purchasing wine, cheese, honey and many other ingredients.</p>

<p>Our approach towards the operation of the restaurant is truly cooperative. We believe that every single member of our staff is integral to our success and pay sustainable living wages to all employees, offering medical benefits and profit sharing to all full time employees.</p>

<h2>Who lead us</h2>

<p>Our current leaders of kitchen and service at Wok & Wine:</p>

<ul>

<li>Alexander Roberts – Executive Chef / CEO / Proprietor</li>

<li>Mike Berger / General Manager</li>

<li>Lucas Rosenbrook– Chef / Kitchen Manager</li>

<li>James Hirdler – Service Supervisor / Wine Director</li>

<li>Hannah Drehmann – Event Coordinator</li>

<li>Carrie Riggs – Pastry Chef</li>

</ul>

<h2>Alexander Roberts</h2>

<p>Alexander Roberts was born in Buffalo, New York, but his formative years were spent here in Minneapolis. He started working in local kitchens in high school and through college.  In the early 1990’s, Alex moved to New York City, where he attended the French Culinary Institute.  After graduation, Alex gained experience in several renowned New York restaurants, including Gramercy Tavern, Bouley, and the Union Square Cafe.</p>

<p>Alex returned to Minneapolis and opened Restaurant Wok & Wine in 1999. He has been able to advance his commitment to organic, sustainably produced food at Wok & Wine and has received numerous accolades in the process.</p>

<p>Alex opened Brasa Premium Rotisserie in 2007, also committed to organic, sustainably produced food. For more details about Brasa please call 612-379-3030 or visit their website at www.brasa.us.</p>

restapp-sprint1/app/views/pages/contact_us.html.erb
<%= content_for :header_title do %>
    Contact us 
<% end %>

<%= content_for :header_sub_title do %>
    Find us here 
<% end %>

restapp-sprint1/app/views/pages/faq.html.erb
<%= content_for :header_title do %>

    Frequently Asked Questions 

<% end %>

<%= content_for :header_sub_title do %>

    Your doubts, clarified 

<% end %>

<p><strong>What hours are the Restaurant open for dining?</strong></p>

<p>Lunch Hours: Monday through Friday | 11:30am to 2:00pm, and Dinner Hours: Tuesday through Saturday | 5:30pm to 9:00pm. Our Restaurant lounge is always open during our dining hours.</p>

<p><strong>Do you have to be a member to dine at Wok & Wine ?</strong></p>

<p>We welcome non-members to try the restaurant for lunch or dinner on a one time basis, but we do require membership for continuous usage and always give priority seating to our members.</p>

<p><strong>Do Wok & Wine members get a discount?</strong></p>

<p>Yes, all Wok & Wine members receive a 10% discount on food and beverage purchases in the restaurant.</p>

<p><strong>Are there any blackout dates for the restaurant?</strong></p>

<p>Our online calendar (click here) is always kept up to date with the latest sold out dates and times. The restaurant is typically closed the week after the October and May races for post-race clean up. Wok & Wine is not open on Sundays except for special occasions.</p>

<p><strong>Should I make a reservation?</strong></p>

<p>Yes, we recommend making a reservation in order to give you the best possible service and ensure that we have your desired time available. We do accept walk-ins unless we are sold out for a private function.</p>

<p><strong>What is the easiest way to make reservations?</strong></p>

<p>To make a reservation, please call the main restaurant line at 704-455-3216. You can also click here to make an online reservation request.</p>

<p><strong>What is the dress code for the restaurant?</strong></p>

<p>Find details about our dress code by clicking here.</p>

<p><strong>Will Wok & Wine do anything special for a birthday or anniversary?</strong></p>

<p>Wok & Wine members can receive a complimentary 6-inch white cake for a birthday or anniversary when they make a dinner reservation. A minimum 48-hour notice is required. Depending on availability, a balloon bouquet can also be placed at the guest's table. Cakes can also be pre-ordered for a fee determined by the size and type of cake requested.</p>

<p><strong>Can a non-member make a dining reservation during race?</strong></p>

<p>Non-members can only make a reservation during ticketed events if they are a guest of a member or have a ticket in Wok & Wine Convention Center. Event tickets are required by all in order to dine in the restaurant during the event.</p>

restapp-sprint1/app/views/pages/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->

  <ol class="carousel-indicators">

    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>

    <li data-target="#carousel-example-generic" data-slide-to="1"></li>

    <li data-target="#carousel-example-generic" data-slide-to="2"></li>

  </ol>

  <!-- Wrapper for slides -->

  <div class="carousel-inner" role="listbox">

    <div class="item active">

      <%= image_tag "rest_slider1.jpg", html: { alt: "rest_slider1" } %>

      <div class="carousel-caption">

        <h3>Our restaurants</h3>

        <p>The best for you</p>

      </div>

    </div>

    <div class="item">

      <%= image_tag "rest_slider2.jpg", html: { alt: "rest_slider2" } %>

      <div class="carousel-caption">

        <h3>Our service</h3>

        <p>Best quality</p>

      </div>

    </div>

    <div class="item">

      <%= image_tag "rest_slider3.jpg", html: { alt: "rest_slider3" }%>

      <div class="carousel-caption">

        <h3>Our service</h3>

        <p>Best quality</p>

      </div>

    </div>

  </div>

  <!-- Controls -->

  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">

    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>

    <span class="sr-only">Previous</span>

  </a>

  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">

    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>

    <span class="sr-only">Next</span>

  </a>

</div>

restapp-sprint1/app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :born_at, as: :date %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

restapp-sprint1/app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

restapp-sprint1/app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Born at</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.born_at %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

restapp-sprint1/app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

restapp-sprint1/app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>Born at:</strong>
  <%= @profile.born_at %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>